"""
app/ingestion/cleaning_service.py

WHY THIS FILE EXISTS
---------------------
Implements the "Cleaning" stage of the ingestion pipeline - both
PyMuPDF's native extraction and Tesseract's OCR output are RAW text
full of artifacts (irregular whitespace, hyphenation breaks across
line wraps, control characters, repeated page-number-only lines) that
would otherwise get embedded verbatim, degrading both embedding
quality and the readability of any chunk text later shown to a user
as part of a citation. This service is the ONE place text is
normalized before chunking, so both the PDF-native and OCR text paths
go through IDENTICAL cleaning logic - important because OCR output in
particular is much noisier and would otherwise need bespoke handling
that the chunker (which should not need to know or care where its
input text came from) would have to work around.

WHY this is a deterministic, dependency-free implementation (pure
Python regex, no ML/model calls): cleaning must be fast (it runs on
every page of every document) and perfectly reproducible - the exact
same input text must always produce the exact same cleaned output, so
re-ingesting an unmodified document never silently produces different
chunks.
"""

import re
import unicodedata

from app.core.base_service import BaseService
from app.core.constants import PipelineStage
from app.core.exceptions import ChunkingError

# WHY these specific patterns, in this specific order (see `clean`
# below for the order they're actually applied in):
#
# 1. Hyphenated line-wrap repair: PDF text extraction frequently
#    breaks a word across two lines with a trailing hyphen
#    ("mainte-\nnance" -> should read "maintenance"). Left unrepaired,
#    this fragments a real word into two out-of-vocabulary-looking
#    tokens for the embedding model.
_HYPHEN_LINEBREAK_PATTERN = re.compile(r"(\w)-\n(\w)")

# 2. Collapse any run of whitespace (including newlines) into a single
#    space - EXCEPT we handle paragraph breaks (double newlines)
#    separately first, below, so real paragraph structure isn't lost
#    before we get here.
_MULTIPLE_BLANK_LINES_PATTERN = re.compile(r"\n\s*\n+")
_INTRA_LINE_WHITESPACE_PATTERN = re.compile(r"[ \t\r\f\v]+")

# 3. Lines that are ENTIRELY a bare page number (optionally with
#    "Page"/"page" prefix) - extremely common boilerplate on every
#    page of a PDF that adds zero semantic value and, worse, would
#    otherwise appear as noise inside a chunk if that chunk happens to
#    start or end near a page boundary.
_PAGE_NUMBER_ONLY_LINE_PATTERN = re.compile(
    r"^\s*(page\s*)?\d{1,5}\s*(of\s*\d{1,5})?\s*$", re.IGNORECASE | re.MULTILINE
)

# 4. Control characters (excluding the newline/tab we intentionally
#    keep) that OCR output in particular can occasionally contain from
#    misrecognized glyphs.
_CONTROL_CHAR_PATTERN = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")


class TextCleaningService(BaseService):
    """
    Normalizes raw extracted/OCR'd page text into clean, chunk-ready
    text.
    """

    def clean(self, text: str) -> str:
        """
        Apply the full cleaning pipeline to one page (or document
        section) of raw text.

        Args:
            text: Raw text from `TextExtractionService` or
                `OCRService`.

        Returns:
            Cleaned text - repaired hyphenation, normalized Unicode,
            collapsed whitespace, page-number-only lines removed,
            control characters stripped, leading/trailing whitespace
            trimmed.

        Raises:
            ChunkingError: if `text` is not a string, or cleaning
                otherwise fails unexpectedly. WHY this reuses
                `ChunkingError` rather than a dedicated
                `CleaningError`: the spec's Error Handling section
                does not call out cleaning as its own failure mode
                distinct from chunking, and a cleaning failure here
                has the exact same downstream consequence (the
                document cannot proceed to chunking) - introducing a
                fourth exception type for a stage with no meaningfully
                different recovery path would add hierarchy without
                adding value.
        """
        if not isinstance(text, str):
            raise ChunkingError(
                "TextCleaningService.clean() received non-string input.",
                stage=PipelineStage.CLEANING,
                details={"received_type": type(text).__name__},
            )

        try:
            # WHY NFKC normalization specifically: it folds visually-
            # equivalent but differently-encoded Unicode characters
            # (e.g. full-width digits, ligatures like "ﬁ" -> "fi",
            # various dash/quote variants) into a single canonical
            # form. Without this, the SAME word encoded two different
            # ways across two documents (common with PDFs generated by
            # different tools) would embed as subtly different text.
            normalized = unicodedata.normalize("NFKC", text)

            repaired = _HYPHEN_LINEBREAK_PATTERN.sub(r"\1\2", normalized)
            no_control_chars = _CONTROL_CHAR_PATTERN.sub("", repaired)
            no_page_numbers = _PAGE_NUMBER_ONLY_LINE_PATTERN.sub("", no_control_chars)

            # WHY paragraph breaks are collapsed to a single "\n\n"
            # (not removed entirely) BEFORE intra-line whitespace
            # collapsing: preserving paragraph boundaries keeps the
            # chunker's token stream readable text (a wall of run-on
            # text with no paragraph structure is harder for the LLM
            # to reason about once it lands inside an answer's cited
            # context), while still eliminating excessive blank lines.
            paragraphs_normalized = _MULTIPLE_BLANK_LINES_PATTERN.sub(
                "\n\n", no_page_numbers
            )
            single_spaced = _INTRA_LINE_WHITESPACE_PATTERN.sub(
                " ", paragraphs_normalized
            )

            # Trim trailing whitespace on each line, then trim the
            # whole result.
            lines = [line.rstrip() for line in single_spaced.split("\n")]
            cleaned = "\n".join(lines).strip()
        except Exception as exc:
            raise ChunkingError(
                "Unexpected failure while cleaning extracted text.",
                stage=PipelineStage.CLEANING,
                original_exception=exc,
            ) from exc

        return cleaned

    def health_check(self) -> dict:
        """
        Verifies the cleaning pipeline behaves correctly on a small,
        known-answer probe string covering every rule above.
        """
        probe = "Page 1\n\nThis is main-\ntenance   text.\n\n\n\nPage 2 of 10"
        expected_fragment = "This is maintenance text."
        try:
            result = self.clean(probe)
            healthy = expected_fragment in result and "Page 1" not in result
            return {
                "service": self.service_name,
                "healthy": healthy,
                "details": {"probe_output": result},
            }
        except ChunkingError as exc:
            return {
                "service": self.service_name,
                "healthy": False,
                "details": {"error": exc.message},
            }
